### ISSUE TITLE
Protvec links broken

### ISSUE THREAD

**Issue by CuypersBart** [hzi-bifo/epitope-prediction#7]
Hi!

The links to the files in the folder 'protvec' seem to be broken. 
Could you repair them? 

Best,

Bart

**Comment by akashbahai** [comment]
Hi @CuypersBart,
Thanks for pointing this out. You can download the required binary file from [here](https://drive.google.com/file/d/18QxzWTpHge03k7DU0MNS8aCfHqmuzmFh/view), while we work on a more permanent solution.

**Comment by akashbahai** [comment]
The wget link has now been updated.
